update code and optimice

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -1,31 +1,75 @@
-# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
-
-name: Node.js CI
+name: Jonowoods Backend CI/CD
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ['main']
   pull_request:
-    branches: [ "main" ]
+    branches: ['main']
 
 jobs:
   build:
-
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
 
     strategy:
       matrix:
-        node-version: [18.x, 20.x, 22.x]
-        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
+        node-version: [22.x]
 
     steps:
-    - uses: actions/checkout@v4
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v4
-      with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'npm'
-    - run: npm ci
-    - run: npm run build --if-present
-    - run: npm test
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: npm
+
+      - name: Check Node and npm versions
+        run: |
+          node -v
+          npm -v
+
+      - name: Install Dependencies
+        run: npm ci
+        working-directory: ${{ github.workspace }}
+
+      - name: Conditionally Install PM2 Globally
+        run: |
+          if ! command -v pm2 &> /dev/null; then
+            echo "PM2 not found, installing globally..."
+            npm install -g pm2
+          else
+            echo "PM2 already installed"
+          fi
+
+      - name: Audit Dependencies
+        run: npm audit --audit-level=moderate
+        working-directory: ${{ github.workspace }}
+
+      - name: Clean Build Folder
+        run: rm -rf dist
+        working-directory: ${{ github.workspace }}
+
+      - name: Format Code
+        run: npm run format
+        working-directory: ${{ github.workspace }}
+
+      - name: Build TypeScript
+        run: npm run build
+        working-directory: ${{ github.workspace }}
+
+      - name: Start or Reload PM2 App
+        run: |
+          sleep 3
+          if pm2 list | grep -q "jonowoods-backend"; then
+            echo "App found, reloading..."
+            pm2 reload jonowoods-backend
+          else
+            echo "App not found, starting..."
+            pm2 start dist/server.js --name jonowoods-backend
+          fi
+        working-directory: ${{ github.workspace }}
+
+
+      - name: Save PM2 State
+        run: pm2 save
